// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: util/proto/assign_op.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "util/proto/assign_op.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PS {

namespace {

const ::google::protobuf::EnumDescriptor* AssignOpType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_util_2fproto_2fassign_5fop_2eproto() {
  protobuf_AddDesc_util_2fproto_2fassign_5fop_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "util/proto/assign_op.proto");
  GOOGLE_CHECK(file != NULL);
  AssignOpType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_util_2fproto_2fassign_5fop_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_util_2fproto_2fassign_5fop_2eproto() {
}

void protobuf_AddDesc_util_2fproto_2fassign_5fop_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032util/proto/assign_op.proto\022\002PS*`\n\014Assi"
    "gnOpType\022\n\n\006ASSIGN\020\000\022\010\n\004PLUS\020\001\022\t\n\005MINUS\020"
    "\002\022\t\n\005TIMES\020\003\022\n\n\006DIVIDE\020\004\022\007\n\003AND\020\005\022\006\n\002OR\020"
    "\006\022\007\n\003XOR\020\007", 130);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "util/proto/assign_op.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_util_2fproto_2fassign_5fop_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_util_2fproto_2fassign_5fop_2eproto {
  StaticDescriptorInitializer_util_2fproto_2fassign_5fop_2eproto() {
    protobuf_AddDesc_util_2fproto_2fassign_5fop_2eproto();
  }
} static_descriptor_initializer_util_2fproto_2fassign_5fop_2eproto_;
const ::google::protobuf::EnumDescriptor* AssignOpType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AssignOpType_descriptor_;
}
bool AssignOpType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PS

// @@protoc_insertion_point(global_scope)
