// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: util/proto/assign_op.proto

#ifndef PROTOBUF_util_2fproto_2fassign_5fop_2eproto__INCLUDED
#define PROTOBUF_util_2fproto_2fassign_5fop_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace PS {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_util_2fproto_2fassign_5fop_2eproto();
void protobuf_AssignDesc_util_2fproto_2fassign_5fop_2eproto();
void protobuf_ShutdownFile_util_2fproto_2fassign_5fop_2eproto();


enum AssignOpType {
  ASSIGN = 0,
  PLUS = 1,
  MINUS = 2,
  TIMES = 3,
  DIVIDE = 4,
  AND = 5,
  OR = 6,
  XOR = 7
};
bool AssignOpType_IsValid(int value);
const AssignOpType AssignOpType_MIN = ASSIGN;
const AssignOpType AssignOpType_MAX = XOR;
const int AssignOpType_ARRAYSIZE = AssignOpType_MAX + 1;

const ::google::protobuf::EnumDescriptor* AssignOpType_descriptor();
inline const ::std::string& AssignOpType_Name(AssignOpType value) {
  return ::google::protobuf::internal::NameOfEnum(
    AssignOpType_descriptor(), value);
}
inline bool AssignOpType_Parse(
    const ::std::string& name, AssignOpType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AssignOpType>(
    AssignOpType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace PS

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PS::AssignOpType>() {
  return ::PS::AssignOpType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_util_2fproto_2fassign_5fop_2eproto__INCLUDED
